# Generated by Django 4.1 on 2022-09-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheets_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер в таблице')),
                ('order', models.CharField(max_length=150, verbose_name='Заказ №')),
                ('price', models.CharField(blank=True, max_length=150, null=True, verbose_name='Стоимость')),
                ('delivery_time', models.CharField(blank=True, max_length=150, null=True, verbose_name='Срок поставки')),
                ('exchange_rate', models.CharField(blank=True, max_length=150, null=True, verbose_name='Обменный курс')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курс валют',
            },
        ),
    ]
